version: 2.1

executors:
  default-executor:
    docker:
      - image: circleci/golang:1.12

jobs:
  build:
    executor: default-executor
    steps:
      - checkout
      - run:
          name: build
          command: make build
      - persist_to_workspace:
          root: dist
          paths:
            - build
  test:
    executor: default-executor
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - run:
          name: test
          command: make test
  deploy:
    executor: default-executor
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - run:
          name: deploy
          command: |
            VERSION=`echo ${CIRCLE_TAG} | perl -pe 's/^deploy\/(.*)$/$1/'`
            if [${VERSION} != '']; then
              make VERSION=${VERSION} deploy
            else
              exit 1
            fi

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^deploy\/.*$/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /^deploy\/.*$/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^deploy\/.*$/
            branches:
              ignore: /.*/

