executors:
  default:
    docker:
      - image: circleci/golang:1.12
    working_dir:
      - /tmp


jobs:
  build:
    executor: default
    steps:
      - checkout
      - run:
          name: build
          command: make build
      - persist_to_workspace:
          root: dist
          paths:
            - build
  test:
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/dist
      - run:
          name: test
          command: make test
  deploy:
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/dist
      - run:
          name: deploy
          command: make deploy
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^deploy\/.*$/

